function consumption=snw_hh_consumption(j,a,eta,educ,married,kids,aprime,...
    theta, r, agrid, epsilon, eta_H_grid, eta_S_grid, SS, Bequests, bequests_option,...
    jret,a2,...
    xi,b)

if nargin==18
	[inc,earn]=snw_hh_individual_income(j,a,eta,educ,...
        theta, r, agrid, epsilon, eta_H_grid, SS, Bequests, bequests_option);
    spouse_inc=snw_hh_spousal_income(j,educ,kids,earn,SS(j,educ),jret);
                                                              
    consumption=(1+r)*(agrid(a)+Bequests*(bequests_option-1))...
        +epsilon(j,educ)*theta*exp(eta_H_grid(eta))...
        +SS(j,educ)+...
        (married-1)*spouse_inc*exp(eta_S_grid(eta))...
        -max(0,snw_tax_hh(inc,(married-1)*spouse_inc*exp(eta_S_grid(eta)),a2))-aprime;
    
elseif nargin==20
    
 	[inc,earn]=snw_hh_individual_income(j,a,eta,educ,...
        theta, r, agrid, epsilon, eta_H_grid, SS, Bequests, bequests_option,...
        xi,b);
    spouse_inc=snw_hh_spousal_income(j,educ,kids,earn,SS(j,educ),jret);

    consumption=(1+r)*(agrid(a)+Bequests*(bequests_option-1))...
        +(epsilon(j,educ)*theta*exp(eta_H_grid(eta)) )*(xi+b*(1-xi))...
        +SS(j,educ)...
        +(married-1)*spouse_inc*exp(eta_S_grid(eta))*(xi+b*(1-xi))...
        -max(0,snw_tax_hh(inc,(married-1)*spouse_inc*exp(eta_S_grid(eta))*(xi+b*(1-xi)),a2))-aprime;
    
else
    error('Incorrect number of function inputs')
end

end